chatgpt_insts = {
    'ag_news': [
        "What label best describes this news article?",
        "What is this piece of news regarding?",
        "Which newspaper section would this article likely appear in?",
        "What topic is this news article about?",
        "What category fits this news piece?",
        "Which label suits this news story best?",
        "What classification would you give to this news article?",
        "What's the best descriptor for this news item?",
        "Regarding what is this news piece?",
        "What subject does this news article cover?",
        "What is the focus of this news story?",
        "What matter is this news article about?",
        "In which part of the newspaper would this article be found?",
        "Where in the newspaper would you expect to find this article?",
        "What theme does this news article follow?",
        "What is the main topic of this news report?",
        "What is this news item about?",
        "Which part of the newspaper is most suitable for this article?",
        "What type of news does this article represent?",
        "What is the subject of this news story?",
        "What area does this news article pertain to?",
        "What is the central theme of this news piece?",
        "In which newspaper division would this article likely appear?",
        "What is the general topic of this news article?",
        "What genre does this news story belong to?",
        "What is the main subject of this news item?",
        "What topic is being covered in this news article?",
        "In what section would this news piece be most appropriately placed?",
        "What news category does this article fall under?",
        "What is the central focus of this news report?",
        "Which newspaper area would feature this article?",
        "What is the key topic of this news story?",
        "What is the primary subject of this news piece?",
        "In which section of the newspaper would you find this article?",
        "What kind of news is this article presenting?",
        "What is the significant topic of this news item?",
        "Which category best fits this news story?",
        "What is the main point of this news article?",
        "In which newspaper column would this article appear?",
        "What is the theme of this news piece?",
        "What is the essential subject of this news article?",
        "Which part of the newspaper would include this article?",
        "What is the central idea of this news story?",
        "What type of content does this news article have?",
        "What subject matter is addressed in this news article?",
        "What is the headline topic of this news item?",
        "Which newspaper feature would this article be a part of?",
        "What is the overarching theme of this news story?",
        "In which newspaper segment would you expect this article?",
        "What is the principal theme of this news piece?",
        "What content category does this news article belong to?",
        "What is the focus area of this news report?",
        "Which section is most appropriate for this news article?",
        "What is the core topic of this news story?",
        "What classification is suitable for this news item?",
        "What is the major subject of this news article?",
        "In what newspaper part would this article be included?",
        "What is the predominant theme of this news piece?",
        "Which newspaper department would carry this article?",
        "What is the significant content of this news story?",
        "What category of news does this article represent?",
        "What is the primary focus of this news report?",
        "In which newspaper category would this article fit?",
        "What is the central theme of this news article?",
        "What genre of news is this article about?",
        "What is the headline focus of this news story?",
        "In which newspaper section is this article best suited?",
        "What overarching subject does this news piece cover?",
        "Which segment of the newspaper is appropriate for this article?",
        "What principal topic does this news item discuss?",
        "What category does this news report belong to?",
        "What area of interest does this news article focus on?",
        "Which part of the newspaper is ideal for this article?",
        "What core subject is covered in this news story?",
        "What suitable classification does this news item have?",
        "What major theme does this news article explore?",
        "In what part of the newspaper would this article fit?",
        "What predominant subject is this news piece about?",
        "Which department of the newspaper would feature this article?",
        "What significant topic does this news report cover?",
        "What kind of news is represented in this article?",
        "What primary area does this news story focus on?",
        "Which category of the newspaper would include this article?",
        "What is the key focus of this news article?",
        "What type of news story is this article presenting?",
        "What is the headline subject of this news item?",
        "In which section of the newspaper should this article be placed?",
        "What overarching topic does this news piece address?",
        "Which part of the newspaper is most fitting for this article?",
        "What principal subject is this news item about?",
        "What category does this news story fall under?",
        "What focus does this news article have?",
        "Which section of the newspaper is best for this article?",
        "What is the core theme of this news story?",
        "What classification best fits this news item?",
        "What is the major focus of this news article?",
        "In what segment of the newspaper would you find this article?",
        "What predominant topic does this news piece discuss?",
        "Which department in the newspaper would this article appear?",
        "What is the significant theme of this news report?",
        "What type of news does this article depict?",
        "What primary topic is this news story about?",
        "Which newspaper category is suitable for this article?",
        "What is the key subject of this news article?"
    ],
    'imdb': [
        "This movie review expresses what sentiment?",
        "Did the reviewer find this movie good or bad?",
        "Is this review positive or negative?",
        "How does the viewer feel about the movie?",
        "What sentiment does the writer express for the movie?",
        "What sentiment is expressed for the movie?",
        "What is the sentiment expressed in this text?",
        "Did the reviewer enjoy the movie?",
        "What is the sentiment expressed by the reviewer for the movie?",
        "How does the reviewer feel about the movie?",
        "What is the overall tone of this movie review?",
        "How does the author of the review perceive the film?",
        "Is the sentiment conveyed in the review positive, negative, or neutral?",
        "Can you identify the reviewer's attitude towards the movie?",
        "What kind of sentiment is being expressed about the movie in this review?",
        "Does the review suggest the movie is worth watching?",
        "How enthusiastic is the reviewer about recommending the movie?",
        "What emotions does the reviewer express regarding the movie?",
        "Is the movie review leaning more towards praise or criticism?",
        "How satisfied does the reviewer seem with the movie?",
        "Does the text reflect a favorable or unfavorable view of the movie?",
        "What is the reviewer's opinion on the film's quality?",
        "How does the review rate the movie's entertainment value?",
        "What feedback does the reviewer give about the movie's plot?",
        "How does the reviewer assess the performances of the actors?",
        "What are the key points of praise or criticism mentioned in the review?",
        "How compelling does the reviewer find the movie?",
        "Does the reviewer mention any memorable moments from the film?",
        "How does the review summarize the movie's impact?",
        "What adjectives does the reviewer use to describe the movie?",
        "How does the reviewer critique the movie's direction?",
        "What is the reviewer's take on the movie's cinematography?",
        "How does the review evaluate the movie's soundtrack?",
        "Does the reviewer comment on the originality of the movie?",
        "What aspects of the movie does the reviewer highlight as strengths or weaknesses?",
        "How does the review compare the movie to others in its genre?",
        "What expectations does the reviewer set for potential viewers?",
        "Does the reviewer discuss the movie's pacing and narrative flow?",
        "How does the reviewer address the movie's thematic elements?",
        "What insights does the review offer about the movie's target audience?",
        "Does the reviewer provide a nuanced perspective on the movie?",
        "How does the review discuss the movie's cultural or historical significance?",
        "What is the reviewer's stance on the movie's visual effects?",
        "How does the review reflect on the movie's emotional depth?",
        "What is the reviewer's critique of the screenplay or script?",
        "Does the review mention any standout performances by the cast?",
        "How does the reviewer evaluate the movie's contribution to its genre?",
        "What are the most memorable quotes or scenes mentioned in the review?",
        "How does the review address any controversies or debates surrounding the movie?",
        "Does the reviewer offer any comparisons to the movie's source material, if applicable?",
        "How does the review articulate the movie's appeal or lack thereof?",
        "What is the reviewer's perspective on the movie's pacing?",
        "How does the reviewer discuss the movie's relevance or message?",
        "Does the review provide any insights into the director's style or vision?",
        "How does the reviewer assess the movie's impact on its audience?",
        "What does the review say about the movie's production values?",
        "How does the review critique the movie's character development?",
        "Does the reviewer discuss the movie's use of humor, if applicable?",
        "How does the review evaluate the movie's setting and world-building?",
        "What is the reviewer's opinion on the movie's climax and resolution?",
        "Does the review address the movie's appeal to a specific demographic?",
        "How does the reviewer discuss any innovative aspects of the movie?",
        "What does the review say about the movie's pacing and structure?",
        "How does the review comment on the movie's themes and motifs?",
        "Does the review discuss the effectiveness of the movie's dialogue?",
        "How does the reviewer evaluate the movie's suspense or tension?",
        "What is the reviewer's opinion on the movie's overall message?",
        "Does the review provide a critical analysis of the movie's plot twists?",
        "How does the review discuss the movie's visual and auditory experience?",
        "What does the review say about the movie's accessibility to audiences?",
        "How does the reviewer address the movie's emotional impact?",
        "Does the review comment on the movie's alignment with genre conventions?",
        "How does the review evaluate the movie's use of special effects?",
        "What insights does the review offer into the movie's creative process?",
        "How does the reviewer discuss the movie's contribution to cinema?",
        "Does the review mention how the movie handles character arcs?",
        "What does the review say about the movie's coherence and unity?",
        "How does the reviewer critique the movie's handling of complex themes?",
        "Does the review discuss the movie's influence on future films?",
        "How does the reviewer address the movie's balance of drama and action?",
        "What is the reviewer's opinion on the movie's use of symbolism?",
        "Does the review comment on the movie's historical accuracy, if relevant?",
        "How does the review evaluate the movie's appeal beyond its initial release?",
        "What does the review say about the movie's pacing relative to its storyline?",
        "How does the reviewer discuss the movie's portrayal of relationships?",
        "Does the review offer insights into the movie's editing and sequencing?",
        "What is the reviewer's perspective on the movie's innovation or creativity?",
        "How does the review address the movie's contribution to its thematic genre?",
        "Does the review discuss the movie's resonance with contemporary issues?",
        "What does the review say about the movie's casting choices?",
        "How does the reviewer critique the movie's exploration of moral dilemmas?",
        "Does the review comment on the movie's integration of music and sound?",
        "How does the review evaluate the movie's handling of suspense and mystery?",
        "What insights does the review offer about the movie's narrative techniques?",
        "How does the reviewer discuss the movie's approach to storytelling?",
        "Does the review provide a comparison to other works by the same director?",
        "What is the reviewer's opinion on the movie's technical achievements?",
        "How does the review address the movie's engagement with its audience?",
        "Does the review comment on the movie's pacing in building to its climax?",
        "What does the review say about the movie's representation of its themes?"
    ],
    'cola': [
        "Does the this sentence make sense and use correct English?",
        "Is this example grammatically correct and sensible?",
        "Does this sentence make sense and is it grammatically correct?",
        "Does this example use correct English?",
        "Is this sentence grammatically correct and logical?",
        "Does this statement conform to standard English grammar and usage?",
        "Is the grammar and logic of this sentence correct?",
        "Does this text adhere to rules of English syntax and make sense?",
        "Is this sentence constructed with proper English grammar and coherence?",
        "Can this example be considered grammatically sound and meaningful?",
        "Is this utterance correct and reasonable in terms of English grammar?",
        "Does this sentence display proper use of English and logical structure?",
        "Is the English grammar and logic in this sentence correct?",
        "Can this sentence be deemed correct and sensible in English?",
        "Is this sentence logically sound and grammatically correct?",
        "Does this example showcase correct English grammar and sensibility?",
        "Is this statement both grammatically accurate and logically coherent?",
        "Does this sentence correctly follow English grammatical norms and logic?",
        "Is this expression grammatically and logically correct in English?",
        "Does this sentence maintain grammatical integrity and coherence?",
        "Is the construction of this sentence correct and logical in English?",
        "Does this phrase correctly and sensibly use English grammar?",
        "Is this sentence's grammar and logic up to standard?",
        "Can this sentence's English and coherence be considered correct?",
        "Is this example linguistically correct and logical?",
        "Does this sentence demonstrate proper grammar and understanding in English?",
        "Is this sentence accurate and logical with respect to English grammar?",
        "Does this construction reflect correct English grammar and coherence?",
        "Is the English and logic of this sentence properly maintained?",
        "Does this statement uphold grammatical correctness and sensibility?",
        "Is this sentence's structure both correct and reasonable?",
        "Does this line adhere to grammatical correctness and logical sense?",
        "Is this sentence's use of English both correct and logical?",
        "Can this statement be validated for grammar and logic in English?",
        "Is this example grammatically valid and sensible?",
        "Does this sentence comply with correct English usage and logic?",
        "Is this declaration grammatically and logically sound?",
        "Does this proposition maintain correctness and sensibility in English?",
        "Is this sentence's formulation correct and sensible?",
        "Does this expression make grammatical and logical sense?",
        "Is this sentence logically and grammatically up to the mark?",
        "Does this example uphold English grammatical standards and logic?",
        "Is this phrase correct in grammar and reason?",
        "Can this sentence's grammar and logic be affirmed as correct?",
        "Is this utterance sensible and correct in grammatical terms?",
        "Does this statement make grammatical sense and logical coherence?",
        "Is this sentence's English grammar and logic effectively applied?",
        "Does this text exhibit proper grammatical and logical structure?",
        "Is this construction grammatically correct and logically structured?",
        "Does this sentence's grammar and logic stand correct?",
        "Is this sentence appropriately correct and logical in English?",
        "Does this example properly use grammar and logic?",
        "Is this statement logically coherent and grammatically accurate?",
        "Does this sentence blend grammatical correctness with logical sense?",
        "Is this expression valid in terms of grammar and logic?",
        "Does this sentence align with grammatical and logical correctness?",
        "Is this phrase constructed with proper grammar and logic?",
        "Does this sentence hold up grammatically and logically?",
        "Is this example both logically sound and grammatically correct?",
        "Does this statement follow the principles of grammar and logic correctly?",
        "Is this sentence logically valid and grammatically accurate?",
        "Does this utterance use English grammar and logic correctly?",
        "Is this declaration both grammatically and logically appropriate?",
        "Does this sentence satisfy grammatical and logical standards?",
        "Is this proposition correct in grammar and reasoning?",
        "Does this line make sense and adhere to grammatical rules?",
        "Is this sentence's grammar and reasoning correctly applied?",
        "Does this expression meet grammatical and logical criteria?",
        "Is this sentence structurally and logically correct?",
        "Does this text demonstrate grammatical correctness and logical sense?",
        "Is this construction logically coherent and grammatically sound?",
        "Does this sentence maintain coherence and grammatical accuracy?",
        "Is this sentence grammatically and logically precise?",
        "Does this phrase make correct use of English grammar and logic?",
        "Is this statement's grammar and logic adequately correct?",
        "Does this sentence present a grammatically sound and logical argument?",
        "Is this utterance both coherent and grammatically correct?",
        "Does this declaration exhibit correct grammar and logical reasoning?",
        "Is this proposition logically and grammatically well-formed?",
        "Does this line use correct English and logical structure?",
        "Is this sentence's construction grammatically and logically valid?",
        "Does this expression convey correct grammar and sensible logic?",
        "Is this sentence logical and grammatically correct by English standards?",
        "Does this example adhere to grammatical correctness and logical reasoning?",
        "Is this phrase grammatically sound and logically structured?",
        "Does this sentence exhibit logical coherence and grammatical correctness?",
        "Is this statement correct in English grammar and logical reasoning?",
        "Does this sentence achieve grammatical precision and logical clarity?",
        "Is this utterance logically consistent and grammatically sound?",
        "Does this declaration make sense grammatically and logically?",
        "Is this proposition grammatically and logically accurate?",
        "Does this line follow correct grammatical and logical principles?",
        "Is this sentence's grammar and reasoning sound and correct?",
        "Does this expression correctly apply English grammar and logic?",
        "Is this sentence grammatically correct and logically valid?",
        "Does this example conform to grammatical accuracy and logical sense?",
        "Is this phrase logically sound and grammatically precise?",
        "Does this sentence maintain correct use of grammar and logic?",
        "Is this statement grammatically accurate and logically consistent?",
        "Does this sentence correctly interpret English grammar and logic?"
    ],
    "dair-ai/emotion": [
        "What is the emotion expressed in this message?",
        "What emotion does this message express?",
        "How will you feel about the message?",
        "What emotion does the writer express for the message?",
        "What is the emotion expressed in this message?",
        "What emotion does this message express?",
        "How will you feel about the message?",
        "What emotion does the writer express for the message?",
        "Identify the emotion conveyed in the text.",
        "What feeling does this passage evoke?",
        "How would this message make someone feel?",
        "Can you detect the mood of this message?",
        "What sentiment is being expressed here?",
        "Describe the emotional tone of this message.",
        "Which emotion best matches the author's expression?",
        "What is the underlying emotion in this statement?",
        "How does this message make you feel emotionally?",
        "What vibe do you get from this message?",
        "Can you identify the writer's emotional state?",
        "What emotional response does this message provoke?",
        "How would you describe the sentiment of this text?",
        "What is the dominant emotion in this message?",
        "What mood is the author conveying in this message?",
        "Which emotion does this text evoke in you?",
        "How does the message's tone affect its emotional impact?",
        "What emotional undercurrent is present in the message?",
        "Can you sense the emotional intensity of this text?",
        "What is the emotional nuance of this statement?",
        "How does this communication emotionally engage the reader?",
        "What emotional layer can you detect in this message?",
        "Which feeling permeates through this text?",
        "How is emotion portrayed in this message?",
        "What is the sentiment tone of this communication?",
        "How emotionally charged is this message?",
        "Can you pinpoint the emotional flavor of this text?",
        "What emotional color does this message paint?",
        "How does this message resonate emotionally with you?",
        "What is the emotional depth of this statement?",
        "Can you decipher the emotional context of this message?",
        "What feeling is the text trying to convey?",
        "How does the emotional aspect of this message affect you?",
        "What emotional temperature does this message have?",
        "Can you interpret the emotional layering in this text?",
        "What emotional significance does this message hold?",
        "How do the emotions in this message unfold?",
        "What is the emotional wavelength of this communication?",
        "Can you identify the emotional pulse of this text?",
        "What emotional fabric is woven into this message?",
        "How does this narrative evoke emotion?",
        "What emotional intensity is embedded in this message?",
        "Can you sense the emotional vibration of this text?",
        "What emotional essence is captured in this message?",
        "How do you interpret the emotional dimension of this text?",
        "What emotional resonance does this message have?",
        "Can you discern the emotional texture of this message?",
        "What emotional contours does this text outline?",
        "How does this piece emotionally impact the reader?",
        "What emotional range is explored in this message?",
        "Can you gauge the emotional temperature of this text?",
        "What emotional dynamics are at play in this message?",
        "How does this text emotionally engage with its audience?",
        "What emotional landscape is depicted in this message?",
        "Can you trace the emotional trajectory of this text?",
        "What emotional depth is plumbed in this message?",
        "How does the text emotionally connect with the reader?",
        "What emotional richness does this message offer?",
        "Can you feel the emotional pulse in this text?",
        "What emotional strength does this message demonstrate?",
        "How does this message emotionally resonate with you?",
        "What emotional clarity can you find in this text?",
        "Can you identify the emotional undertones in this message?",
        "What emotional vividness is present in this text?",
        "How does the message emotionally appeal to the reader?",
        "What emotional authenticity does this message convey?",
        "Can you detect the emotional sincerity in this text?",
        "What emotional depth does this message explore?",
        "How is the emotional spectrum represented in this message?",
        "What emotional honesty does this text exhibit?",
        "Can you sense the emotional gravity of this message?",
        "What emotional complexity is revealed in this text?",
        "How does this message emotionally differentiate itself?",
        "What emotional insight does this text provide?",
        "Can you feel the emotional weight of this message?",
        "What emotional subtlety is expressed in this text?",
        "How is the emotional narrative constructed in this message?",
        "What emotional balance does this message strike?",
        "Can you appreciate the emotional artistry in this text?",
        "What emotional reflection does this message inspire?",
        "How does this text emotionally unfold for the reader?",
        "What emotional impact does this message aim to have?",
        "Can you understand the emotional implications of this text?",
        "What emotional depth is conveyed in this message?",
        "How does this message emotionally captivate the audience?",
        "What emotional expressiveness is showcased in this text?",
        "Can you explore the emotional dimensions of this message?",
        "What emotional resonance does this narrative hold?",
        "How does this message emotionally challenge the reader?",
        "What emotional engagement does this text encourage?",
        "Can you analyze the emotional discourse in this message?",
        "What emotional richness is embedded in this text?"
    ],
    'offensive': [
        "Is this message offensive?",
        "Does this text contain offensive language?",
        "Is this statement likely to offend someone?",
        "Is this message inappropriate?",
        "Is this text offensive to anyone?",
        "Does this statement contain offensive content?",
        "Is this message likely to cause offense?",
        "Is this text likely to be considered offensive?",
        "Does this statement contain language that might offend?",
        "Is this message likely to be considered offensive?",
        "Does this text contain language that might offend?",
        "Is this statement likely to be considered offensive?",
        "Is this message likely to be offensive to someone?",
        "Does this text contain language that could be offensive?",
        "Is this statement likely to be offensive to someone?",
        "Is this message likely to offend someone?",
        "Does this text contain language that could cause offense?",
        "Is this statement likely to cause offense?",
        "Is this message likely to be offensive to anyone?",
        "Does this text contain language that might cause offense?",
        "Is this statement likely to be offensive?",
        "Is this message likely to be considered offensive to someone?",
        "Does this text contain language that might be offensive?",
        "Is this statement likely to be offensive to anyone?",
        "Is this message likely to be offensive?",
        "Does this text contain language that might be considered offensive?",
        "Is this statement likely to offend someone?",
        "Is this message likely to be considered offensive?",
        "Does this text contain language that might be likely to offend?",
        "Is this statement likely to be considered offensive to someone?",
        "Is this message likely to be offensive to someone?",
        "Does this text contain language that might be likely to cause offense?",
        "Is this statement likely to cause offense?",
        "Is this message likely to be offensive to anyone?",
        "Does this text contain language that might be likely to be offensive?",
        "Is this statement likely to be offensive?",
        "Is this message likely to be considered offensive to someone?",
        "Does this text contain language that might be likely to offend?",
        "Is this statement likely to offend someone?",
        "Is this message likely to be considered offensive?",
        "Does this text contain language that might be likely to cause offense?",
        "Is this statement likely to be considered offensive to someone?",
        "Is this message likely to offend someone?",
        "Does this text contain language that might be offensive?",
        "Is this tweet offensive?",
        "Can the tweet be removed for being offensive?",
        "Is the author's tweet offensive?",
        "Task: Identify if the tweet or text is offensive.",
        "Is this an offensive tweet?",
        "Does this tweet contain offensive content?",
        "Should this tweet be considered offensive?",
        "Could this tweet be deemed offensive?",
        "Is there any offensive language in this tweet?",
        "Does the tweet use language that could offend?",
        "Is the tweet potentially offensive?",
        "Could someone find this tweet offensive?",
        "Is the tweet's message offensive?",
        "Does this tweet share offensive views?",
        "Should the tweet be flagged as offensive?",
        "Is the tweet's tone offensive?",
        "Does this tweet express offensive opinions?",
        "Could the tweet offend certain groups?",
        "Is the humor in this tweet offensive?",
        "Does this tweet make offensive assumptions?",
        "Is the tweet offensive to specific communities?",
        "Could the tweet's sarcasm be offensive?",
        "Is the tweet disrespectful or offensive?",
        "Does this tweet belittle or offend?",
        "Should this tweet's language be considered offensive?",
        "Is the tweet's critique offensive?",
        "Does the tweet contain potentially offensive stereotypes?",
        "Could the tweet's imagery be offensive?",
        "Is the tweet's portrayal of cultures offensive?",
        "Does this tweet use derogatory terms?",
        "Is the tweet's joke considered offensive?",
        "Could the tweet's content be seen as offensive?",
        "Is the tweet's reference offensive?",
        "Does the tweet mock or ridicule?",
        "Should the tweet's perspective be deemed offensive?",
        "Is the tweet's commentary offensive?",
        "Does the tweet disrespect any beliefs or practices?",
        "Could the tweet's humor offend some audiences?",
        "Is the tweet's language derogatory or offensive?",
        "Does this tweet undermine dignity or respect?",
        "Should the tweet's message be flagged for offensiveness?",
        "Is the tweet's satire potentially offensive?",
        "Does the tweet contain offensive implications?",
        "Could the tweet's critique be considered offensive?",
        "Is the tweet's portrayal of events offensive?",
        "Does the tweet trivialize sensitive issues?",
        "Should the tweet's analogy be seen as offensive?",
        "Is the tweet's depiction of relationships offensive?",
        "Does this tweet exhibit offensive bias?",
        "Could the tweet's view on social issues be offensive?",
        "Is the tweet's discussion of political matters offensive?",
        "Does the tweet use language offensive to minorities?",
        "Should the tweet's portrayal of progress be questioned for offensiveness?",
        "Is the tweet's approach to diversity offensive?",
        "Does this tweet disrespect cultural or social norms?",
        "Could the tweet's commentary on health or wellness be offensive?",
    ],
    'gimmaru/newspop': [
        "What is the article about?",
        "What is this news about?",
        "What is the topic of this news piece?",
        "What does this article discuss?",
        "What is the topic of this sentence?",
        "What category does the article belong to?",
        "Pick one category for this news piece.",
        "Pick the category that fits the text.",
        "The article refers to which category?",
        "What topic does the article belong to?",
        "What category fits this article?",
        "What topic does this news piece belong to?",
        "Choose the correct category for this article.",
        "What is the main focus of this article?",
        "Can you summarize the theme of this news?",
        "What subject does this article cover?",
        "Identify the central topic of this news piece.",
        "What area does this article delve into?",
        "What is the essence of this news story?",
        "What field does this news article belong to?",
        "Determine the category for this piece of news.",
        "What is the news article discussing?",
        "Classify the news piece into a category.",
        "What significant topic is this article about?",
        "What is the core subject of this news?",
        "What specific area does this news piece address?",
        "Outline the theme of the article.",
        "Which sector does this news article relate to?",
        "What is the central issue discussed in this news?",
        "Identify the genre of this news story.",
        "What is the primary focus of this article?",
        "Which category best describes this news piece?",
        "What main event does the article report on?",
        "What subject matter does this news piece tackle?",
        "How would you categorize this article?",
        "What is the key topic of this news article?",
        "What category should this news story be classified under?",
        "What is the article highlighting?",
        "Which theme does this news piece revolve around?",
        "What is the main argument of this article?",
        "In which category does this piece of news fit?",
        "What is the headline topic of this news?",
        "What kind of issue does the article address?",
        "What major subject is covered in this news piece?",
        "How is the news article oriented in terms of topic?",
        "What is the central theme of this news story?",
        "Classify this article by its main subject.",
        "Which area does the news piece focus on?",
        "What is the leading topic of this article?",
        "Determine the theme of this news piece.",
        "What category encompasses this news article?",
        "What is the focal point of this news story?",
        "Which domain does the article pertain to?",
        "What is the chief topic of this news piece?",
        "Select the most fitting category for this article.",
        "What major theme does the article discuss?",
        "In what context does this news piece fall?",
        "What primary subject does the news article explore?",
        "Choose the appropriate category for this news story.",
        "What is the article's main message?",
        "Which field does this piece of news highlight?",
        "What is the predominant theme of this article?",
        "Categorize the main subject of this news piece.",
        "What is the essential content of this news?",
        "Which topic is central to this article?",
        "What kind of news does this article present?",
        "What is the article's main point of interest?",
        "Which category fits the news article best?",
        "What is the article's primary concern?",
        "Identify the main topic of this news story.",
        "What category does this article's content belong to?",
        "What main theme is explored in this news piece?",
        "How would you define the topic of this article?",
        "What is the predominant focus of this news?",
        "Which topic category does this news piece fall under?",
        "What central theme does the article address?",
        "Determine the main focus of this news article.",
        "What is the headline subject of this article?",
        "Classify the subject matter of this news piece.",
        "What overarching topic does the article discuss?",
        "Which aspect does this news story concentrate on?",
        "What is the article about in detail?",
        "Pick the most accurate category for this news piece.",
        "What key issue does the news article tackle?",
        "What is the article's main area of focus?",
        "Which category does the news story fit into?",
        "What is the dominant theme of this news piece?",
        "How does the article categorize its main topic?",
        "What is the central point of discussion in this news?",
        "Identify the key focus of this article.",
        "What type of content does this news piece present?",
        "Which main subject does the article explore?",
        "Determine the appropriate category for this news story.",
        "What is the lead topic of this news article?",
        "Classify this news article by its content.",
        "What significant theme is covered in this article?",
        "In what category should this article be placed?",
        "What is the news piece primarily about?",
        "Which specific area does the news article cover?",
        "What major topic does the news story discuss?",
    ],
}